apiVersion: apps/v1
kind: Deployment
metadata:
  name: pahal-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pahal
  template:
    metadata:
      labels:
        app: pahal
    spec:
      containers:
        - name: pahal
          image: registry.gitlab.com/your-username/pahal:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pahal-service
spec:
  selector:
    app: pahal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
